//
// Created by lh001 on 2019/4/17.
//

#ifndef BITCOINDIAMOND_BCDVALIDATION_H
#define BITCOINDIAMOND_BCDVALIDATION_H

static const size_t MAX_CONTRACT_VOUTS = 1000;

#endif //BITCOINDIAMOND_BCDVALIDATION_H
